# Generated by Django 3.0.3 on 2021-05-23 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified_time')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified_time')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified_time')),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified_time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('friends', models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='moviematch.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='created_time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modified_time')),
                ('imdbID', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=500)),
                ('year', models.TextField()),
                ('mpaa_rating', models.TextField(max_length=10)),
                ('release_date', models.TextField()),
                ('runtime', models.TextField()),
                ('director', models.TextField()),
                ('plot', models.TextField(max_length=500)),
                ('country', models.TextField(max_length=20)),
                ('poster_link', models.TextField(max_length=500)),
                ('imdb_rating', models.FloatField()),
                ('medium', models.TextField(max_length=20)),
                ('actors', models.ManyToManyField(blank=True, related_name='media_actor', to='moviematch.Actor')),
                ('genres', models.ManyToManyField(blank=True, related_name='media_genre', to='moviematch.Genre')),
                ('writer', models.ManyToManyField(blank=True, related_name='media_writer', to='moviematch.Writer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
